name: Deploy GH Pages
on:
  push:
    branches: ['main']
jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    
    - name: Deploy to GH Pages
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
